### ISSUE TITLE
best category for DEF CON

### ISSUE THREAD

**Issue by Hauwertlhaufn** [carpedm20/awesome-hacking#16]
They have a lot of lectures and documentaries on their website. ([Media Server](https://media.defcon.org/) and [torrents](https://www.defcon.org/html/links/dc-torrent.html)). What is the best way to handle it? Everything for itself in the now existing categories, or just a single link?

**Comment by n0ncetonic** [comment]
I know this is a super old Issue but I just discovered this repo and I'm trying to help clean things up/answer questions.

I'd say it's pretty difficult to categorize the DEF CON stuff anywhere in particular since talks cover various disciplines (especially now with villages having their talks recorded). 

Personally I'd make a recommendation for @carpedm20 's consideration that we make a new top-level category for Talk and Conference archives. Stuff like DEF CON's media page, [Blackhat's](https://www.blackhat.com/html/bh-media-archives/bh-multi-media-archives.html), and [Infocon's](https://infocon.org/cons/) conference archive would be perfect for this
